### PR TITLE
feat: update papermod

### LINKED ISSUE #77: improper html rendering
image

the date and time field does not render nicely

### PR DESCRIPTION
**Pull request by Jh123x**
Closes #77 

- [x] feat: update papermod
- [ ] fix: fix secweds appearing
- [ ] fix: fix team page
- [ ] fix: fix resources page

### CODE REVIEW

**Comment by caprinux** [comment]
thanks for this :)

but this seems to mess up some other stuff — the secwed posts seem to appear on the front page now. ill look at this when i get home if it's not fixed yet :>

**Comment by daniellimws** [comment]
Yea I modified the original theme a lot. So we can't just merge downstream directly.

**Comment by Jh123x** [comment]
@caprinux @daniellimws I migrated it to used the builtin one instead of the custom one.

Lmk if got other bugs

**Comment by Jh123x** [comment]
Fixed yml pages as well.

Now the theme should be updatable. I moved the templates to the `layouts/_defaults` where they will be searched first before the `theme` files

**Comment by caprinux** [comment]
im trying to re-create the modifications that daniel did before into `layouts/*`, where do css files go?

**Comment by Jh123x** [comment]
> im trying to re-create the modifications that daniel did before into `layouts/*`, where do css files go?

It should be in assets iirc

**Comment by caprinux** [comment]
can't find the offending bracket :( will look again tmrw

**Comment by caprinux** [comment]
TODO: 

- [ ] fix contrasting card colors in light mode
- [ ] fix margins
- [ ] check if everything else is okay T_T

image


image

**Comment by Jh123x** [comment]
> TODO:
> 
> * [x]  fix contrasting card colors in light mode
> * [ ]  fix margins
> * [ ]  check if everything else is okay T_T
> 
> image
> 
> image

For the modes, I added some stuff for light theme so should be ok now?

**Comment by Jh123x** [comment]
image
image

**Comment by caprinux** [comment]
this looks good! might be good to go

**Comment by Jh123x** [comment]
> this looks good! might be good to go

If ok can just merge ba

**Comment by caprinux** [comment]
thanks senpai for ur help! >< @Jh123x

**Pull request merged**
